import OpenAI from "openai";
import { Platform } from "@prisma/client";
import { PLATFORM_CONFIGS } from "@/types/platform";
import {
  BrandContext,
  MOCK_BRAND_CONTEXT,
  buildBrandContextPrompt,
} from "@/types/brand-brain";

/** Per-user brand profile stored in `BrandBrain` (settings), distinct from workspace OrcBrain. */
export interface BrandBrainContext {
  brandName?: string | null;
  industry?: string | null;
  description?: string | null;
  targetAudience?: string | null;
  uniqueValue?: string | null;
  tone?: string | null;
  personality?: string | null;
  writingStyle?: string | null;
  avoidTopics?: string | null;
  keyPhrases?: string | null;
  primaryGoal?: string | null;
  contentPillars?: string | null;
  callToAction?: string | null;
  hashtagStrategy?: string | null;
}

let _openai: OpenAI | null = null;

/**
 * Check if OpenAI is available (API key configured).
 */
export function isOpenAIAvailable(): boolean {
  return Boolean(process.env.OPENAI_API_KEY);
}

/**
 * The AI provider is not configured.
 *
 * Thrown instead of returning synthetic text in production: a mock completion is
 * indistinguishable from a real one once it is in the UI, so silently serving it
 * would misrepresent the product. Local development and tests still get mocks.
 */
export class AINotConfiguredError extends Error {
  readonly code = "AI_NOT_CONFIGURED";
  constructor() {
    super(
      "AI is not configured. Set OPENAI_API_KEY (or AI_API_KEY) to enable AI generation.",
    );
    this.name = "AINotConfiguredError";
  }
}

/** Mock AI output is a development affordance, never a production one. */
export function isMockAIAllowed(): boolean {
  return process.env.NODE_ENV !== "production";
}

function getOpenAI(): OpenAI {
  if (!_openai) {
    if (!process.env.OPENAI_API_KEY) {
      throw new Error("OpenAI API key not configured. Set OPENAI_API_KEY environment variable.");
    }
    _openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
      baseURL: process.env.OPENAI_BASE_URL || "https://api.openai.com/v1",
    });
  }
  return _openai;
}

export interface GeneratedVariant {
  platform: Platform;
  content: string;
  hashtags: string[];
  characterCount: number;
  withinLimit: boolean;
  /** Whether this variant was generated by mock (no OpenAI) */
  isMock?: boolean;
}

export interface AIStudioOptions {
  /** Original content idea to transform */
  idea: string;
  /** Target platforms for variants */
  platforms: Platform[];
  /** Optional tone override */
  tone?: string;
  /** Additional context for generation */
  additionalContext?: string;
  /** Brand Brain context (uses mock if not provided) */
  brandContext?: BrandContext;
  /** Force mock generation even if OpenAI is available (for testing) */
  forceMock?: boolean;
}

const PLATFORM_PROMPTS: Record<Platform, string> = {
  LINKEDIN: `LinkedIn: Professional tone, industry insights, thought leadership. Can use longer form content up to 3000 chars. Include relevant professional hashtags (3-5). Focus on value, expertise, and meaningful engagement.`,
  
  TWITTER: `X/Twitter: Concise, punchy, engaging. MUST be under 280 characters including hashtags. Use 1-3 relevant hashtags. Make it shareable and conversation-starting. Can use emojis sparingly.`,
  
  INSTAGRAM: `Instagram: Visual-first mindset, engaging captions. Up to 2200 chars but sweet spot is 125-150 for feed posts. Use 5-10 relevant hashtags at the end. Conversational, authentic voice. Include call-to-action.`,
  
  FACEBOOK: `Facebook: Conversational and community-focused. Medium length (40-80 words ideal). Use 1-2 hashtags max. Encourage discussion and sharing. Can be more personal and storytelling-oriented.`,
  
  TIKTOK: `TikTok: Trendy, casual, Gen-Z friendly. Short punchy captions under 150 chars. Use 3-5 trending/relevant hashtags. Include hook in first few words. Think video caption style.`,
  
  YOUTUBE: `YouTube: Title-focused (under 100 chars), descriptive. If for video description, include timestamps placeholder, key points, and call-to-action. Use 3-5 relevant tags. SEO-optimized keywords.`,

  TELEGRAM: `Telegram: Direct, useful, community-first. Up to 4096 chars, but keep channel posts scannable (under 500). Light formatting with clear line breaks, 0-2 hashtags, no engagement-bait. Lead with the takeaway or the link. Captions are capped at 1024 chars when media is attached.`,
};

/**
 * Deterministic hash for mock generation — ensures consistent output for the same input.
 */
function simpleHash(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  return Math.abs(hash);
}

/**
 * Platform-specific mock content templates.
 * Uses the idea to generate deterministic but varied content.
 */
const MOCK_TEMPLATES: Record<Platform, (idea: string, brandName: string, hashtags: string[]) => string> = {
  LINKEDIN: (idea, brandName, hashtags) => {
    const lines = [
      `🚀 ${idea}`,
      "",
      `At ${brandName}, we believe in continuous innovation and growth.`,
      "",
      "Here's what we've learned:",
      "→ Focus on value creation",
      "→ Build meaningful connections",
      "→ Stay ahead of the curve",
      "",
      "What's your take on this? Share your thoughts below! 👇",
      "",
      hashtags.map(h => `#${h}`).join(" "),
    ];
    return lines.join("\n");
  },
  
  TWITTER: (idea, brandName, hashtags) => {
    const shortIdea = idea.length > 150 ? idea.substring(0, 147) + "..." : idea;
    const hashtagStr = hashtags.slice(0, 2).map(h => `#${h}`).join(" ");
    return `${shortIdea}\n\n${hashtagStr}`;
  },
  
  INSTAGRAM: (idea, brandName, hashtags) => {
    return `✨ ${idea}\n\nDouble tap if you agree! 💙\n\nFollow @${brandName.toLowerCase().replace(/\s+/g, "")} for more!\n\n${hashtags.map(h => `#${h}`).join(" ")}`;
  },
  
  FACEBOOK: (idea, brandName, hashtags) => {
    return `${idea}\n\nWhat do you think? Let us know in the comments! 💬\n\n${hashtags.slice(0, 2).map(h => `#${h}`).join(" ")}`;
  },
  
  TIKTOK: (idea, _brandName, hashtags) => {
    const shortIdea = idea.length > 80 ? idea.substring(0, 77) + "..." : idea;
    return `${shortIdea} 🔥\n\n${hashtags.slice(0, 4).map(h => `#${h}`).join(" ")}`;
  },
  
  YOUTUBE: (idea, brandName, hashtags) => {
    return `${idea} | ${brandName}\n\nIn this video:\n00:00 Introduction\n01:00 Main Content\n05:00 Key Takeaways\n\nDon't forget to like, subscribe, and hit the bell! 🔔\n\n${hashtags.map(h => `#${h}`).join(" ")}`;
  },
  
  TELEGRAM: (idea, brandName, hashtags) => {
    return `📢 ${idea}\n\nFrom ${brandName}\n\n${hashtags.length > 0 ? hashtags.slice(0, 2).map(h => `#${h}`).join(" ") : ""}`;
  },
};

/**
 * Generate deterministic hashtags based on the idea and platform.
 */
function generateMockHashtags(idea: string, platform: Platform): string[] {
  const baseHashtags = ["growth", "innovation", "success", "business", "strategy", "marketing", "content", "socialmedia"];
  const hash = simpleHash(idea + platform);
  const count = platform === "INSTAGRAM" ? 7 : platform === "TWITTER" ? 2 : 4;
  
  const selected: string[] = [];
  for (let i = 0; i < count; i++) {
    const idx = (hash + i * 7) % baseHashtags.length;
    if (!selected.includes(baseHashtags[idx])) {
      selected.push(baseHashtags[idx]);
    }
  }
  
  return selected;
}

/**
 * Generate mock platform variants without calling OpenAI.
 * Produces deterministic output based on the input for testability.
 */
export function generateMockVariants(options: AIStudioOptions): GeneratedVariant[] {
  const { idea, platforms, brandContext } = options;
  const ctx = brandContext || MOCK_BRAND_CONTEXT;
  const brandName = ctx.profile?.name || "Your Brand";
  
  return platforms.map((platform) => {
    const hashtags = generateMockHashtags(idea, platform);
    const template = MOCK_TEMPLATES[platform];
    const content = template(idea, brandName, hashtags);
    const config = PLATFORM_CONFIGS[platform];
    
    return {
      platform,
      content,
      hashtags,
      characterCount: content.length,
      withinLimit: content.length <= config.maxTextLength,
      isMock: true,
    };
  });
}

/**
 * AI Studio: Generate platform-specific content variants from a single idea.
 * Uses Brand Brain context when available, falls back to mock generation
 * when OpenAI is not configured.
 */
export async function aiStudioGenerate(options: AIStudioOptions): Promise<{
  variants: GeneratedVariant[];
  usedMock: boolean;
  brandContextUsed: boolean;
}> {
  const { idea, platforms, tone, additionalContext, brandContext, forceMock } = options;

  if (forceMock) {
    return {
      variants: generateMockVariants(options),
      usedMock: true,
      brandContextUsed: Boolean(brandContext),
    };
  }

  if (!isOpenAIAvailable()) {
    // Never hand a synthetic variant to production: it reads as real content.
    if (!isMockAIAllowed()) throw new AINotConfiguredError();
    return {
      variants: generateMockVariants(options),
      usedMock: true,
      brandContextUsed: Boolean(brandContext),
    };
  }
  
  const ctx = brandContext || MOCK_BRAND_CONTEXT;
  const brandPrompt = buildBrandContextPrompt(ctx);
  
  const variants = await generatePlatformVariantsWithBrand(
    idea,
    platforms,
    tone,
    additionalContext,
    brandPrompt
  );
  
  return {
    variants,
    usedMock: false,
    brandContextUsed: Boolean(brandContext),
  };
}

/**
 * Internal: Generate variants with Brand Brain context via OpenAI.
 */
async function generatePlatformVariantsWithBrand(
  originalIdea: string,
  platforms: Platform[],
  tone?: string,
  additionalContext?: string,
  brandContextPrompt?: string
): Promise<GeneratedVariant[]> {
  const platformInstructions = platforms
    .map((p) => PLATFORM_PROMPTS[p])
    .join("\n\n");

  const systemPrompt = `You are a social media content expert. Your job is to transform a content idea into platform-optimized posts.
${brandContextPrompt || ""}
For each platform, consider:
- Character limits and formatting constraints
- Platform-specific tone and style
- Hashtag best practices
- Engagement optimization
- Brand voice consistency (if brand context provided)

${platformInstructions}

${tone ? `Desired tone: ${tone}` : ""}
${additionalContext ? `Additional context: ${additionalContext}` : ""}

Respond in JSON format with an array of objects, each containing:
- platform: the platform name (LINKEDIN, TWITTER, INSTAGRAM, FACEBOOK, TIKTOK, YOUTUBE, or TELEGRAM)
- content: the optimized post content (main text without hashtags)
- hashtags: array of hashtags (without # symbol)

Ensure content is properly tailored for each platform's audience and constraints while maintaining brand voice.`;

  const response = await getOpenAI().chat.completions.create({
    model: process.env.OPENAI_MODEL || "gpt-4o-mini",
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: `Original idea:\n\n${originalIdea}` },
    ],
    response_format: { type: "json_object" },
    temperature: 0.7,
  });

  const content = response.choices[0]?.message?.content;
  if (!content) {
    throw new Error("No response from AI");
  }

  const parsed = JSON.parse(content);
  const variants: { platform: string; content: string; hashtags: string[] }[] = parsed.variants || parsed.posts || [];

  return variants.map((v) => {
    const platform = v.platform as Platform;
    const config = PLATFORM_CONFIGS[platform];
    const fullContent = v.hashtags.length > 0
      ? `${v.content}\n\n${v.hashtags.map((h) => `#${h}`).join(" ")}`
      : v.content;
    
    return {
      platform,
      content: fullContent,
      hashtags: v.hashtags,
      characterCount: fullContent.length,
      withinLimit: fullContent.length <= config.maxTextLength,
      isMock: false,
    };
  });
}

/**
 * Generate platform variants (legacy API, now delegates to aiStudioGenerate).
 * Mock-safe: returns deterministic mock variants when OpenAI is not configured.
 */
export async function generatePlatformVariants(
  originalIdea: string,
  platforms: Platform[],
  tone?: string,
  additionalContext?: string
): Promise<GeneratedVariant[]> {
  const result = await aiStudioGenerate({
    idea: originalIdea,
    platforms,
    tone,
    additionalContext,
  });
  return result.variants;
}

/**
 * Mock improvement: applies simple transformations based on instruction keywords.
 */
function mockImproveContent(content: string, instruction: string): string {
  const lowerInstruction = instruction.toLowerCase();
  let improved = content;
  
  if (lowerInstruction.includes("shorter") || lowerInstruction.includes("concise")) {
    const sentences = improved.split(/[.!?]+/).filter(Boolean);
    improved = sentences.slice(0, Math.ceil(sentences.length / 2)).join(". ") + ".";
  }
  
  if (lowerInstruction.includes("emoji") || lowerInstruction.includes("emojis")) {
    if (!improved.includes("✨")) improved = "✨ " + improved;
    if (!improved.includes("🚀")) improved = improved + " 🚀";
  }
  
  if (lowerInstruction.includes("professional")) {
    improved = improved.replace(/!/g, ".");
    improved = improved.replace(/🔥|😊|😎/g, "");
  }
  
  if (lowerInstruction.includes("casual") || lowerInstruction.includes("friendly")) {
    if (!improved.includes("!")) {
      improved = improved.replace(/\.$/, "!");
    }
  }
  
  return `[Mock improved] ${improved}`;
}

/**
 * Improve existing content based on an instruction.
 * Mock-safe: returns deterministic mock improvement when OpenAI is not configured.
 */
export async function improveContent(
  content: string,
  platform: Platform,
  instruction: string,
  forceMock?: boolean
): Promise<{ content: string; isMock: boolean }> {
  if (forceMock) {
    return {
      content: mockImproveContent(content, instruction),
      isMock: true,
    };
  }

  if (!isOpenAIAvailable()) {
    // Same rule as generation: production gets an error, not invented content.
    if (!isMockAIAllowed()) throw new AINotConfiguredError();
    return {
      content: mockImproveContent(content, instruction),
      isMock: true,
    };
  }
  
  const config = PLATFORM_CONFIGS[platform];
  
  const response = await getOpenAI().chat.completions.create({
    model: process.env.OPENAI_MODEL || "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content: `You are a social media content editor. Improve the following ${platform} post based on the user's instruction. Keep it within ${config.maxTextLength} characters. Return only the improved content, nothing else.`,
      },
      {
        role: "user",
        content: `Current content:\n${content}\n\nInstruction: ${instruction}`,
      },
    ],
    temperature: 0.7,
  });

  return {
    content: response.choices[0]?.message?.content || content,
    isMock: false,
  };
}

export async function suggestBestTimes(platform: Platform): Promise<{
  times: { day: string; hour: number; score: number }[];
  notes: string;
}> {
  const bestTimes: Record<Platform, { day: string; hour: number; score: number }[]> = {
    LINKEDIN: [
      { day: "Tuesday", hour: 10, score: 95 },
      { day: "Wednesday", hour: 10, score: 92 },
      { day: "Thursday", hour: 10, score: 90 },
      { day: "Tuesday", hour: 12, score: 88 },
      { day: "Wednesday", hour: 12, score: 85 },
    ],
    TWITTER: [
      { day: "Wednesday", hour: 9, score: 95 },
      { day: "Friday", hour: 9, score: 92 },
      { day: "Tuesday", hour: 10, score: 90 },
      { day: "Thursday", hour: 12, score: 88 },
      { day: "Monday", hour: 9, score: 85 },
    ],
    INSTAGRAM: [
      { day: "Tuesday", hour: 11, score: 95 },
      { day: "Wednesday", hour: 11, score: 93 },
      { day: "Friday", hour: 10, score: 90 },
      { day: "Monday", hour: 11, score: 88 },
      { day: "Thursday", hour: 14, score: 85 },
    ],
    FACEBOOK: [
      { day: "Wednesday", hour: 11, score: 95 },
      { day: "Friday", hour: 10, score: 92 },
      { day: "Monday", hour: 9, score: 90 },
      { day: "Tuesday", hour: 13, score: 88 },
      { day: "Thursday", hour: 11, score: 85 },
    ],
    TIKTOK: [
      { day: "Tuesday", hour: 19, score: 95 },
      { day: "Thursday", hour: 19, score: 93 },
      { day: "Friday", hour: 17, score: 90 },
      { day: "Saturday", hour: 11, score: 88 },
      { day: "Sunday", hour: 19, score: 85 },
    ],
    YOUTUBE: [
      { day: "Thursday", hour: 15, score: 95 },
      { day: "Friday", hour: 15, score: 93 },
      { day: "Saturday", hour: 11, score: 90 },
      { day: "Sunday", hour: 11, score: 88 },
      { day: "Wednesday", hour: 15, score: 85 },
    ],
    TELEGRAM: [
      { day: "Tuesday", hour: 9, score: 93 },
      { day: "Wednesday", hour: 9, score: 91 },
      { day: "Thursday", hour: 18, score: 89 },
      { day: "Monday", hour: 9, score: 87 },
      { day: "Friday", hour: 12, score: 84 },
    ],
  };

  const notes: Record<Platform, string> = {
    LINKEDIN: "B2B audiences most active during business hours. Tuesday-Thursday mornings see highest engagement.",
    TWITTER: "Fast-moving platform. Morning posts catch commuters. Mid-week performs best.",
    INSTAGRAM: "Late morning/lunch breaks ideal. Weekdays outperform weekends for business content.",
    FACEBOOK: "Mid-week, late morning optimal. Avoid posting too early or late.",
    TIKTOK: "Evening hours when users are relaxing. Weekend mornings also perform well.",
    YOUTUBE: "Publish before peak viewing hours (evenings/weekends). Thursday-Saturday optimal.",
    TELEGRAM: "Notifications land immediately, so cadence matters more than timing. Mid-morning and early evening read best; avoid posting more than once a day.",
  };

  return {
    times: bestTimes[platform],
    notes: notes[platform],
  };
}
