"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, BrainCircuit, Check, ChevronRight, Flame, Lightbulb, Menu, Play, Radar, Sparkles, Trophy, X } from "lucide-react";
import { BrandLogo } from "@/components/brand-logo";
import { CharacterCrew } from "@/components/landing/character-crew";

const platforms=[{name:"Instagram",mark:"◎",note:"Visual story ready",score:"92% predicted engagement"},{name:"TikTok",mark:"♪",note:"Hook + video script",score:"Trend matched"},{name:"YouTube",mark:"▶",note:"Title + concept ready",score:"Retention optimized"},{name:"LinkedIn",mark:"in",note:"Thought-leadership post",score:"Voice matched"},{name:"X",mark:"𝕏",note:"High-impact thread",score:"Conversation ready"},{name:"Facebook",mark:"f",note:"Community version",score:"Ready to publish"}];

function FloatingNav(){const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);useEffect(()=>{const onScroll=()=>setScrolled(scrollY>30);onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>removeEventListener("scroll",onScroll)},[]);const links=["Product","AI Crew","Integrations","Solutions","Pricing","Resources"];return <header className={`mk-nav ${scrolled?"is-scrolled":""}`}><div className="mk-nav-inner"><BrandLogo/><nav aria-label="Main navigation">{links.map(x=><a key={x} href={`#${x.toLowerCase().replace(" ","-")}`}>{x}</a>)}</nav><div className="mk-nav-actions"><Link href="/login">Log in</Link><Link href="/register" className="mk-button mk-button-small">Start for free</Link></div><button className="mk-menu" aria-label="Toggle menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav className="mk-mobile-nav">{links.map(x=><a key={x} onClick={()=>setOpen(false)} href={`#${x.toLowerCase().replace(" ","-")}`}>{x}</a>)}<Link href="/register">Start for free</Link></nav>}</header>}

const nodePositions=[[89,50],[69.5,82.91],[30.5,82.91],[11,50],[30.5,17.09],[69.5,17.09]];
const routePaths=["M300 260 Q379 303 495 260","M300 260 Q302 350 398 412","M300 260 Q223 307 203 412","M300 260 Q221 217 105 260","M300 260 Q298 170 203 108","M300 260 Q377 213 398 108"];
function CommandCenter(){const[active,setActive]=useState(0);return <div className="mk-command" aria-label="Interactive Social Command Center"><div className="mk-core"><span>SO</span><strong>SocialOrk</strong><small>BRAND BRAIN</small><i/></div><svg className="mk-routes" viewBox="0 0 600 520" aria-hidden="true">{routePaths.map((path,i)=><path key={path} className={active===i?"active":""} d={path}/>)}</svg>{platforms.map((p,i)=><button key={p.name} className={`mk-node ${active===i?"active":""}`} style={{left:`${nodePositions[i][0]}%`,top:`${nodePositions[i][1]}%`}} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)}><b>{p.mark}</b><span>{p.name}</span><div><strong>{p.note}</strong><small>{p.score}</small></div></button>)}<div className="mk-packet packet-a"/><div className="mk-packet packet-b"/></div>}

function Hero(){const lines=["One intelligent crew.","One command center.","One brain behind it all."];const[line,setLine]=useState(0);useEffect(()=>{const id=setInterval(()=>setLine(v=>(v+1)%lines.length),3200);return()=>clearInterval(id)},[]);return <section className="mk-hero" id="product"><div className="mk-aurora"/><div className="site-width mk-hero-grid"><div className="mk-hero-copy"><span className="mk-eyebrow"><Sparkles/> THE SOCIAL MEDIA AI OS</span><h1>Your entire<br/>social world.<br/><em key={line}>{lines[line]}</em></h1><p>Create, schedule, publish and grow everywhere from one AI-powered command center. SocialOrk turns your brand knowledge into content built for every platform.</p><div className="mk-actions"><Link href="/register" className="mk-button">Build my AI crew <ArrowRight/></Link><a href="#one-idea" className="mk-button mk-button-ghost"><Play/> Watch SocialOrk work</a></div><small>No credit card required <i/> Connect your first platform in minutes</small></div><CommandCenter/></div><div className="mk-scroll-cue">SCROLL TO ENTER THE COMMAND CENTER <ChevronRight/></div></section>}

function ProblemAndTransform(){const outputs=["Instagram / visual caption + hashtags","TikTok / hook + short-form script","YouTube / title + thumbnail concept","LinkedIn / thought-leadership post","X / high-impact thread","Facebook / community-first version"];return <><section className="mk-problem"><div className="site-width"><span className="mk-eyebrow dark">THE TOOL SPRAWL ENDS HERE</span><h2>Social media shouldn&apos;t<br/>require 12 different tools.</h2><div className="mk-chaos"><div><p>Creating in one app.</p><p>Scheduling in another.</p><p>Analytics somewhere else.</p><p>Copying ideas into five platforms.</p></div><div className="mk-collapse"><span>Canva</span><span>Buffer</span><span>Analytics</span><span>ChatGPT</span><span>Notes</span><div><img src="/socialork-logo.svg" alt=""/><b>One intelligent system.</b></div></div></div></div></section><section id="one-idea" className="mk-transform"><div className="site-width"><span className="mk-eyebrow">ONE IDEA → EVERYWHERE</span><h2>Perfectly adapted.<br/>Never copy-pasted.</h2><div className="mk-transform-grid"><div className="mk-idea"><Lightbulb/><span>YOUR IDEA</span><p>“Launch our new AI productivity feature.”</p></div><div className="mk-process"><BrainCircuit/><b>SocialOrk is adapting</b><i/><i/><i/></div><div className="mk-outputs">{outputs.map((text,i)=><article key={text}><b>{platforms[i].mark}</b><span>{text}</span><Check/></article>)}</div></div></div></section></>}

function SharedBrain(){const knowledge=["Brand voice","Products","Audience","Campaigns","Visual identity","Goals","Past content","Performance data"];return <section className="mk-brain"><div className="site-width mk-brain-grid"><div><span className="mk-eyebrow">ONE SHARED INTELLIGENCE</span><h2>They don&apos;t just know AI.<br/><em>They know you.</em></h2><p>Teach SocialOrk your brand once. Every specialist uses the same context from then on.</p><div className="mk-knowledge">{knowledge.map(x=><span key={x}>{x}</span>)}</div></div><div className="mk-brain-card"><div><BrainCircuit/><strong>87%</strong><span>Brand understanding</span></div>{["Voice learned","Audience learned","Visual system learned","Goals learned"].map(x=><p key={x}><Check/>{x}</p>)}</div></div></section>}

function DashboardPreview(){return <section className="mk-showcase"><div className="site-width"><span className="mk-eyebrow dark">LIVE COMMAND CENTER</span><h2>Your social world.<br/>Under control.</h2><div className="mk-browser"><header><i/><i/><i/><span>app.socialork.com</span></header><div className="mk-dash"><aside><BrandLogo compact/>{["Home","Create","AI Crew","Calendar","Analytics","Campaigns","Brain","Inbox","Explore"].map((x,i)=><span key={x} className={i===0?"active":""}>{x}</span>)}</aside><main><p>GOOD MORNING, HASSAN</p><h3>Your social world is looking strong.</h3><div className="mk-metrics">{[["7","Connected platforms"],["12","Scheduled posts"],["+24%","Engagement"],["3","Growth opportunities"]].map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div><div className="mk-insight"><Sparkles/><div><span>OPPORTUNITY DETECTED</span><strong>Your LinkedIn audience is 34% more responsive to AI automation content.</strong></div><button>Create a post</button></div><div className="mk-dash-bottom"><article><h4>Publishing rhythm</h4><div className="mk-chart">{[1,2,3,4,5,6,7].map(x=><i key={x}/>)}</div></article><article><h4>AI suggestions</h4><p>Double down on tutorials <ArrowRight/></p><p>Fill tomorrow&apos;s LinkedIn slot <ArrowRight/></p></article></div></main></div></div></div></section>}

function IntelligenceSections(){const[optimized,setOptimized]=useState(false);return <><section className="mk-loop site-width"><div><span className="mk-eyebrow">THE INTELLIGENCE LOOP</span><h2>Every post makes<br/>the next one smarter.</h2><p>SocialOrk creates, adapts, publishes, learns and improves as one continuous system.</p></div><div className="mk-loop-ring">{["Create","Adapt","Publish","Learn","Improve"].map((x,i)=><span key={x} className={`loop-${i}`}>{String(i+1).padStart(2,"0")}<b>{x}</b></span>)}<BrainCircuit/></div></section><section className="mk-calendar"><div className="site-width mk-calendar-grid"><div><span className="mk-eyebrow dark">SMART CALENDAR</span><h2>Your calendar<br/>thinks ahead.</h2><p>Every audience has its own rhythm. SocialOrk learns it.</p><button className="mk-button" onClick={()=>setOptimized(!optimized)}><Sparkles/> {optimized?"Optimized":"AI Optimize"}</button></div><div className={`mk-week ${optimized?"optimized":""}`}>{["MON","TUE","WED","THU","FRI"].map((d,i)=><div key={d}><b>{d}</b>{i!==3&&<article style={{marginTop:`${[70,28,92,50,42][i]}px`}}><span>{platforms[i].mark}</span><p>{optimized?["18:42","20:15","07:50","","17:30"][i]:["14:00","16:00","08:30","","15:00"][i]}</p>{optimized&&<small>+{[27,19,14,0,22][i]}%</small>}</article>}</div>)}</div></div></section><section className="mk-intelligence site-width"><div className="mk-pulse"><Radar/><span>SOCIALORK PULSE</span><h2>Know what&apos;s about to matter.</h2><div className="mk-radar"><i/><i/><i/><b>AI workflows ↑ 84%</b><b>Founder stories ↑ 31%</b><b>Tutorial Shorts ↑ 46%</b></div></div><div className="mk-actions-panel"><BarChart3/><span>ANALYTICS THAT ACT</span><h2>Numbers should tell you what to do next.</h2>{["Tutorials outperform announcements by 42%","LinkedIn engagement is rising","Your 25–34 audience grew 18%"].map(x=><button key={x}>{x}<ArrowRight/></button>)}</div></section><section className="mk-game site-width"><div><span className="mk-eyebrow">PROGRESS WITH PURPOSE</span><h2>Growing should<br/>feel rewarding.</h2><p>Professional momentum, made visible.</p></div><div className="mk-achievement"><Trophy/><span>ACHIEVEMENT UNLOCKED</span><h3>Omnipresent</h3><p>Published across 5 platforms</p><b>+250 XP</b><div><Flame/> 12 day consistency streak</div></div></section></>}

function FinalSections(){return <><section id="pricing" className="mk-pricing site-width"><span className="mk-eyebrow">START WHERE YOU ARE</span><h2>A crew that grows with you.</h2><div>{["Creator","Growth","Team","Enterprise"].map((x,i)=><article key={x} className={i===1?"featured":""}>{i===1&&<span>MOST POPULAR</span>}<h3>{x}</h3><p>{["For building a personal brand.","For serious multi-platform growth.","For collaborative marketing teams.","For complex organizations."][i]}</p><Link href="/register">{i===3?"Talk to us":"Start free"}<ArrowRight/></Link></article>)}</div><small>Cancel anytime. Exact plan details will be published before billing begins.</small></section><section className="mk-final"><div className="site-width"><div className="mk-final-orbit"><img src="/socialork-logo.svg" alt="Animated SocialOrk intelligence core"/>{platforms.map((p,i)=><span key={p.name} className={`final-${i}`}>{p.mark}</span>)}</div><span className="mk-eyebrow">YOUR CREW IS READY</span><h2>Your audience is everywhere.<br/><em>Your team shouldn&apos;t have to be.</em></h2><p>Create once. Think smarter. Grow everywhere.</p><div className="mk-actions"><Link href="/register" className="mk-button">Build your AI crew <ArrowRight/></Link><a href="#product" className="mk-button mk-button-ghost">See SocialOrk in action</a></div><small>No credit card required.</small></div></section><footer className="mk-footer site-width"><div><BrandLogo/><p>The AI Operating System for Social Media.</p></div><div>{["Product","AI Crew","Integrations","Solutions","Resources","Company","Legal"].map(x=><a key={x} href="#product">{x}</a>)}</div><p>Made with ⚔️ for people building audiences everywhere.</p><small>© {new Date().getFullYear()} SocialOrk</small></footer></>}

export function LandingV1(){return <div className="mk-site"><a href="#main-content" className="skip-link">Skip to content</a><FloatingNav/><main id="main-content"><Hero/><ProblemAndTransform/><div id="ai-crew"><CharacterCrew/></div><SharedBrain/><DashboardPreview/><IntelligenceSections/><FinalSections/></main><div className="mk-progress" aria-hidden="true"/></div>}
