import type { EmergingNetworkCard } from "./types";

/** Static emerging-network mocks — no live crawl. */
export const MOCK_EMERGING_NETWORKS: EmergingNetworkCard[] = [
  {
    id: "bluesky",
    name: "Bluesky",
    handleHint: "@you.bsky.social",
    audienceFit: 72,
    growthSignal: 81,
    maturity: "growing",
    priority: "experiment-early",
    whyNow: "Creator density still low in B2B niches; discovery favors early posters (mock).",
    experimentIdea: "Ship 3 short founder threads this week; measure follows from warm intros.",
  },
  {
    id: "threads",
    name: "Threads",
    handleHint: "@you",
    audienceFit: 68,
    growthSignal: 74,
    maturity: "growing",
    priority: "experiment-early",
    whyNow: "Cross-posting from IG is cheap; text-first formats underused in your category (mock).",
    experimentIdea: "Repurpose one LinkedIn carousel as a 5-post Threads run; track saves.",
  },
  {
    id: "mastodon",
    name: "Mastodon",
    handleHint: "@you@instance",
    audienceFit: 55,
    growthSignal: 48,
    maturity: "nascent",
    priority: "watch",
    whyNow: "Strong tech communities, slower growth; worth a presence, not a campaign bet (mock).",
    experimentIdea: "Join one relevant instance and mirror weekly product notes.",
  },
  {
    id: "lemmy",
    name: "Lemmy",
    handleHint: "u/you",
    audienceFit: 41,
    growthSignal: 39,
    maturity: "nascent",
    priority: "defer",
    whyNow: "Sparse brand-safe communities for your ICP right now (mock).",
    experimentIdea: "Park a watchlist; revisit if a target community crosses 5k actives.",
  },
  {
    id: "nostr",
    name: "Nostr",
    handleHint: "npub…",
    audienceFit: 36,
    growthSignal: 44,
    maturity: "nascent",
    priority: "watch",
    whyNow: "Protocol curiosity is high; distribution still thin for B2B (mock).",
    experimentIdea: "Publish a single long-form note; no cadence commitment yet.",
  },
];
