"use client";

import { useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { ArrowLeft, Globe2, Loader2, MapPin, Save, UserRound } from "lucide-react";
import { Header } from "@/components/dashboard/header";
import { OrcMark } from "@/components/icons/orc-mark";

type Profile = { id: string; name: string | null; email: string | null; image: string | null; headline: string | null; bio: string | null; location: string | null; website: string | null; coverImageUrl: string | null; role: string; createdAt: string };
type Post = { id: string; content: string; platform: string; status: string; createdAt: string };

export default function ProfilePage() {
  const [profile, setProfile] = useState<Profile | null>(null), [posts, setPosts] = useState<Post[]>([]);
  const [form, setForm] = useState({ name: "", headline: "", bio: "", location: "", website: "", image: "", coverImageUrl: "" });
  const [editing, setEditing] = useState(false), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { void (async () => { try { const response = await fetch("/api/profile"); const data = await response.json(); if (!response.ok) throw new Error(data.error); setProfile(data.profile); setPosts(data.posts); setForm({ name: data.profile.name || "", headline: data.profile.headline || "", bio: data.profile.bio || "", location: data.profile.location || "", website: data.profile.website || "", image: data.profile.image || "", coverImageUrl: data.profile.coverImageUrl || "" }); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load your profile."); } finally { setLoading(false); } })(); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch("/api/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setProfile(data.profile); setEditing(false); setMessage("Profile saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save your profile."); } finally { setSaving(false); } }
  if (loading) return <><Header title="Profile" /><div className="feed-loading"><Loader2 className="animate-spin" /> Loading profile…</div></>;
  if (!profile) return <><Header title="Profile" /><div className="feed-alert">{message || "Profile unavailable."}</div></>;
  return <div className="profile-page"><Header title="Your Profile" description="Shape the identity behind your social presence." /><div className="profile-shell">
    <Link href="/dashboard/feed" className="profile-back"><ArrowLeft size={14} /> Back to timeline</Link>
    <section className="profile-hero"><div className="profile-cover" style={profile.coverImageUrl ? { backgroundImage: `url(${profile.coverImageUrl})` } : undefined} /><div className="profile-hero-body"><span className="feed-avatar feed-avatar-profile">{profile.image ? <img src={profile.image} alt="" /> : <OrcMark className="h-9 w-8" />}</span><div className="profile-hero-copy"><h1>{profile.name || "Your name"}</h1><p>{profile.headline || "Social media commander"}</p><small><span>{profile.role}</span>{profile.location && <><MapPin size={12} />{profile.location}</>}</small></div><button className="profile-edit-button" onClick={() => setEditing(value => !value)}><UserRound size={14} /> {editing ? "Close editor" : "Edit profile"}</button></div><div className="profile-stats"><span><strong>{posts.length}</strong>Posts</span><span><strong>{posts.filter(post => post.status === "PUBLISHED").length}</strong>Published</span><span><strong>{new Date(profile.createdAt).toLocaleDateString(undefined, { month: "short", year: "numeric" })}</strong>Joined</span></div></section>
    {message && <div className="studio-notice" role="status">{message}</div>}
    {editing && <form className="profile-editor" onSubmit={save}><div className="profile-editor-heading"><div><h2>Edit profile</h2><p>These details appear beside your posts.</p></div><button className="settings-save" disabled={saving || !form.name.trim()}>{saving ? <Loader2 size={14} className="animate-spin" /> : <Save size={14} />} Save profile</button></div><div className="profile-form-grid"><label>Name<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} maxLength={80} required /></label><label>Headline<input value={form.headline} onChange={event => setForm({ ...form, headline: event.target.value })} maxLength={140} placeholder="What do you do?" /></label><label>Location<input value={form.location} onChange={event => setForm({ ...form, location: event.target.value })} maxLength={120} placeholder="City, country" /></label><label>Website<input value={form.website} onChange={event => setForm({ ...form, website: event.target.value })} maxLength={300} placeholder="https://…" /></label><label className="profile-form-wide">Bio<textarea value={form.bio} onChange={event => setForm({ ...form, bio: event.target.value })} maxLength={1000} rows={4} placeholder="Tell your audience what you are building." /></label><label>Profile image URL<input value={form.image} onChange={event => setForm({ ...form, image: event.target.value })} placeholder="https://…" /></label><label>Cover image URL<input value={form.coverImageUrl} onChange={event => setForm({ ...form, coverImageUrl: event.target.value })} placeholder="https://…" /></label></div></form>}
    <div className="profile-content-grid"><section className="profile-about"><h2>About</h2><p>{profile.bio || "Add a short bio to make your profile feel like you."}</p>{profile.website && <a href={profile.website} target="_blank" rel="noreferrer"><Globe2 size={13} /> {profile.website}</a>}</section><section className="profile-posts"><div className="profile-section-heading"><h2>Recent posts</h2><Link href="/dashboard/feed">View timeline</Link></div>{posts.length === 0 ? <div className="profile-no-posts">Your published and drafted posts will appear here.</div> : posts.map(post => <article key={post.id}><div><span>{post.platform}</span><small>{new Date(post.createdAt).toLocaleDateString()}</small></div><p>{post.content}</p><em>{post.status.replaceAll("_", " ")}</em></article>)}</section></div>
  </div></div>;
}
